### ISSUE TITLE
Sometimes the player flight group is created twice when starting from a carrier

### ISSUE THREAD

**Issue by akaAgar** [akaAgar/briefing-room-for-dcs#30] opened 2021-01-03 23:27 UTC

**Comment by davidp57** [comment] 2021-01-26 16:17
I spent some time and could not reproduce this ; could you be more specific please @akaAgar ?

**Comment by akaAgar** [comment] 2021-01-26 20:35
Happend twice to me: a perfect clone of the player's FG (same units, same ID) was spawned on the home land airbase and was visible on the mission editor. It didn't pose any problem once the mission started though, as groups and units with duplicate IDs are automatically removed.

**Comment by davidp57** [comment] 2021-01-26 20:59
Ah, I tested in game ; it didn't occur to me to check in the editor. I'll try that.

**Comment by john681611** [comment] 2021-01-26 23:40
I've never seen this but tbh I bearly look at the editor.

**Comment by VCW3-admin** [comment] 2021-03-27 19:46
I've seen this two. Just today I created a mission with a carrier and it created two carriers.

**Comment by john681611** [comment] 2021-03-27 20:01
was this with 2 player groups

**Comment by VCW3-admin** [comment] 2021-03-27 20:10
> was this with 2 player groups

It is with multiplayer. [http://www.virtualcarrierwing3.net/wp-content/uploads/2021/03/carrier-x2.png](url)

**Comment by john681611** [comment] 2021-03-27 20:18
Yeah, this may be an issue with spawning a carrier per flight group.

**Comment by VCW3-admin** [comment] 2021-03-27 20:23
Thanks. It's fixed but not in this release? Is there something that can be edited to change it.

**Comment by john681611** [comment] 2021-03-27 20:25
Next release hopefully.  Unfortunately not  it is in the compiled code unless you can get a version running from the source code

**Comment by VCW3-admin** [comment] 2021-03-27 20:26
> Next release hopefully. Unfortunately not it is in the compiled code unless you can get a version running from the source code

Ok thanks for the info. Looking forward to the next release.

**Comment by john681611** [comment] 2021-05-07 08:28
Can this be considered done?

**Comment by john681611** [comment] 2021-07-18 13:08
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.

**Closed by john681611** 2021-07-18 13:08 UTC
Labels: In Beta, bug
