### ISSUE TITLE
Only one Mig-29 variant available

### ISSUE THREAD

**Issue by dvorgaz** [akaAgar/briefing-room-for-dcs#776] opened 2023-11-08 10:13 UTC
### Brief Description: 
 Only the Mig-29A variant is available from the aircraft drop-down menu

### Expected: 
The Mig-29G and Mig-29S variant should also be available

**Comment by john681611** [comment] 2023-11-09 16:58
IIRC the issue is that those units are not configured correctly in DCS so we can't get the correct data for them: https://github.com/john681611/dcs-data-miner/blob/main/tables/Planes.lua#L7C5-L7C28

**Comment by john681611** [comment] 2023-11-09 20:52
Released in this beta:  https://github.com/akaAgar/briefing-room-for-dcs/releases/tag/beta-release-231109-191104-6816414729-1

**Closed** 2024-01-01 21:51 UTC
Labels: bug, In Beta
