### ISSUE TITLE
"Objetive Count" Parameter

### ISSUE THREAD

**Issue by SpartanEsp** [akaAgar/briefing-room-for-dcs#139] opened 2021-04-03 16:48 UTC
Objetive Count should not control both number of objetives ( waypoints ) and number of targets because it is very difficult to predict how many bombs or missiles you should carry or how many wingmans

There should be 2 different config options for that:

Nº of Strike Locations: Number of strike locations ( waypoints ) that will available on the mission

Nº of Targets: Number of targets to destroy that will be on each objetive ( random number with min/max defined by the player ) ( 2-6 )

**Comment by john681611** [comment] 2021-04-05 15:45
Objectives count only determines the number of instances of an objective with a respective waypoint.  The number of targets is defined in the objective config, the config also defines if AA defensive units are counted as targets too or not.

This request is a duplicate of #82 closing this so we only have one to track

**Closed by john681611** 2021-04-05 15:45 UTC
