### ISSUE TITLE
Tanker Texaco

### ISSUE THREAD

**Issue by ocgadmin** [akaAgar/briefing-room-for-dcs#68] opened 2021-01-31 05:03 UTC
checked again Texaco in the ME is listed as a F/A-18. Not a problem its still is a tanker and, helo's spawn inside hangers.
viacom (voice attack) doesn't seem to work for players using VR
![Texaco as F-18](https://user-images.githubusercontent.com/49978449/106375151-d35de380-63dd-11eb-8bff-1b3e2efcc5e9.jpg)

**Comment by john681611** [comment] 2021-01-31 10:55
can you re-word this I'm struggling to understand the issue here. Looks like the SEAD aircraft has been named Texaco. I'm assuming its still conflicting with the Tanker

**Comment by ocgadmin** [comment] 2021-01-31 11:33
Instead of KC135MPRS or KC-135 the Type displayed is F/A-18. easy fix in the ME

**Comment by john681611** [comment] 2021-01-31 14:55
That aircraft is not supposed to be a tanker you can see its configured as a SEAD aircraft. This just looks like the texico name is assigned to that group too.

**Comment by akaAgar** [comment] 2021-01-31 15:06
That's weird, tanker/AWACS names should not be assigned to other aircraft types. I'll look into this. Did this happen only once or can you reproduce the problem?

**Comment by ocgadmin** [comment] 2021-01-31 20:05
Hard to explain but. ok it seems when selecting different aircraft in the ME. I selected (blue, planes only) and moved between them. the previously selected plane is displayed. new miz attached
  
[Operation Green Clay.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/5900540/Operation.Green.Clay.zip)

**Comment by john681611** [comment] 2021-02-07 11:30
Manually checked mission file no F-18 is even spawned think this may be linked to #76

**Closed** 2021-02-07 12:34 UTC
