### ISSUE TITLE
Correct the carrier group route

### ISSUE THREAD

**Issue by davidp57** [akaAgar/briefing-room-for-dcs#61] opened 2021-01-26 14:44 UTC
Right now the units sail against the wind at constant speed ; the angle of the runway should be taken into account, and the speed computed from the wind speed so a 25 kn speed is attained on deck.

I've done this in LUA, I can do the same in C# I guess ^^

**Comment by akaAgar** [comment] 2021-01-26 20:30
Oh if you feel like coding this that would be great! I guess a "runway angle" property should be added to the ship's unit .ini files to make adding new ships easier

**Comment by davidp57** [comment] 2021-01-26 21:00
I'm on it !

**Comment by john681611** [comment] 2021-01-26 23:40
Currently, the ships aren't moving. Shouldn't be hard to set the ship to move in the direction of the wind. The problem is that because we don't know where the ship is relative to the land we have no idea if the ship is gonna ground by a reasonable mission completion time.

You should be able to get an indication of the nearest land point in that general direction if one exists.

**Comment by john681611** [comment] 2021-02-06 14:56
Fixed with this #77

**Closed** 2021-04-18 06:58 UTC
