### ISSUE TITLE
Suggestion: Add label settings into the options

### ISSUE THREAD

**Issue by jkaryan** [akaAgar/briefing-room-for-dcs#150] opened 2021-04-15 15:40 UTC
### Issue:

Spotting stuff in the game can be HARD, and many like to run with labels, or just the dot. This setting is partially controlled by the mission file, and (EDIT: Not one that actually works and overrides the .miz file, to my knowledge at least) can't be forced from the server. Of course it's possible to edit the mission file after generating it, but doing that means you have to visit the mission editor, and may end up seeing things that "ruin" the mission for you (locations of enemy targets on the map, etc.).

### Solution:

Add a configuration option in to enable/force labels in the mission.

**Background:**
We've been playing together with a friend of mine, and due to his monitors being a bit old he struggles a lot with spotting targets, especially aerial ones. We'd love to run with dot labels on, but getting them to show up requires me to pop into the mission editor to enable them. When the mission is based on figuring out where the targets are, having them show up in the mission editor plain to see sort of spoils the surprise.

**Comment by john681611** [comment] 2021-04-15 22:22
I don't think the setting is applied to the mission (I know it can be). It can be set on the server as it was set on our server for a long time, I think the update has wiped that setting outpost update. I'll try and post the setting location when I find it again,

**Comment by jkaryan** [comment] 2021-04-16 00:20
The setting is in the Config/options.lua (or the "options" file in the .miz):

["difficulty"] = 
    {
        ["labels"] = 4,
    },

I have adjusted this for my server and for my client, but unless I also set it for the mission, I haven't been able to get the dots to actually show up.

**Comment by PSYKO-nz** [comment] 2021-04-17 07:54
WORKAROUND:

I’ve had no issues getting them to work by editing the missions options directly, I use labels 3 for dots only.

You do not have to use the mission editor, just use winrar or open the .miz file and edit the options with notepad. 

I’ve been making adjustments to the options in this way while the dev team get round to adding this stuff in, takes seconds to do.

I’m sure the devs will get round to this when they can, if it can be done. There doing great work and this workaround has helped me with settings for my server. All players are able to see the dots.

keep up the excellent work devs!

**Comment by john681611** [comment] 2021-04-17 17:26
Ok yeah confirmed on our server it seems to have no labels at all.

**Comment by john681611** [comment] 2021-04-17 18:35
Seems the issue is with the Options.lua file turning labels off seems to set the server to the same settings.

**Comment by john681611** [comment] 2021-04-17 18:55
Checkout this Test build
https://github.com/akaAgar/briefing-room-for-dcs/releases/tag/test-net5-210417-1804

**Comment by PSYKO-nz** [comment] 2021-04-21 09:46
tested, something must be off, mission will not load on server

**Comment by john681611** [comment] 2021-04-22 17:20
Try this build. Seems to have F-14 with chaff loaded
https://github.com/akaAgar/briefing-room-for-dcs/releases/tag/test-net5-210422-1704

**Comment by PSYKO-nz** [comment] 2021-04-22 23:11
2021-04-22 23:00:55.077 INFO    Dispatcher: loadMission C:\Users\NZArmA\Saved Games\DCS.openbeta_server\Missions\Briefing Room Missions\Operation Auburn Homecoming.miz
2021-04-22 23:00:55.082 INFO    WORLDGENERAL: loading mission from: "C:\Users\NZArmA\Saved Games\DCS.openbeta_server\Missions\Briefing Room Missions\Operation Auburn Homecoming.miz"
2021-04-22 23:00:55.430 INFO    DCS: use_xRay: yes
2021-04-22 23:00:55.430 INFO    DCS: netfm_enable_coeff_switching: yes
2021-04-22 23:00:55.434 ERROR   Dispatcher: Mission Load Error: Cannot mission: luaL_loadbuffer() returned [string "mission"]:370: unexpected symbol near '['

2021-04-22 23:00:55.434 INFO    NET: Registering server as 115.188.233.151:10308 (port is forwarded by UPNP)
2021-04-22 23:00:55.439 ERROR   Lua::Config: Call error get_server_info:?:0: attempt to index global 'mission' (a nil value).
2021-04-22 23:00:55.439 WARNING NET: Failed to get_server_info()
2021-04-22 23:00:55.439 ERROR   NET: Failed assert `0` at Projects\AsyncNet\src\DsbNet\Mission.cpp:69
2021-04-22 23:01:02.803 INFO    NET: server has stopped
2021-04-22 23:01:02.803 INFO    NET: server has started
2021-04-22 23:01:02.805 INFO    NET: Using LEDBAT for UDP congestion control.
2021-04-22 23:01:02.805 INFO    NET: Successfully set up Dual-Stack socket, using both IPv4 and IPv6
2021-04-22 23:01:02.805 INFO    NET: Listen to IPv6 on port 10308


i also get the same error trying to launch it in sp
[Operation Auburn Homecoming.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/6361717/Operation.Auburn.Homecoming.zip)

**Comment by john681611** [comment] 2021-04-23 08:23
You got a template file to share too

**Comment by PSYKO-nz** [comment] 2021-04-23 08:26
Not yet. I just test with it on random, I’ll set up a template tomorrow for testing, but at this stage the 2 beta builds I’ve tried have those errors in them

**Comment by jkaryan** [comment] 2021-04-27 20:50
FWIW btw I've been testing various methods of setting the labels via the files directly, including setting my client's options.lua, my server's options.lua and the .miz file's options file to the same various label settings, but none of them stick. So far the ONLY way I've found to actually change the label settings properly, and have it stick, has been to launch the in-game mission editor, and change it there.

Like, even if I have a .miz file where labels have been saved to DOT NEUTRAL (labels=4) in the mission editor, I open it in 7z, edit the options file in it to say "labels=1" (for full labels), and then open it again in the Mission Editor, it still says "DOT NEUTRAL".

So it would seem like there's SOMETHING somewhere that's still controlling the labels beyond the setting in the options file, which sounds impossible, to be honest...

**Comment by jkaryan** [comment] 2021-04-27 21:57
Also this might be a coincidence, might not be...

I tried the test build available here: https://github.com/akaAgar/briefing-room-for-dcs/releases/tag/test-net5-210417-1804

When I tried to open the mission generated by that in the mission editor, it gave me an error. I unfortunately didn't think to grab a screenshot, but it said something about having either an [ or an ] in an unexpected position.

Anyway, after that, I haven't been able to open missions in mission editor at all. When you open the mission editor, you have the create new and open mission buttons, the create new works just fine, but the open mission one doesn't do anything. In the File menu at the top all options except exit are greyed out.

If I create a new mission and open the File menu, Open is there as an option, but if I click on it the only thing that happens is that the "Open mission" icon on the left side of the screen changes color, but nothing opens.

This extends also to creating a server inside the game: If I try to create a server, and hit the + button to try and add a mission onto the playlist, nothing happens.

I've tried verifying my files, some got fixed, but it did not help with the issue. Might have to wipe the whole installation, hoping it won't come to that though. Just a word of warning to others tempted to try the experimental build. Not sure it's related, but the timing fits and I can't think of anything else.

**Comment by PSYKO-nz** [comment] 2021-04-27 22:00
That sounds like the error I’ve been having, I’ve posted the log info and also the missions related to the log error

**Comment by jkaryan** [comment] 2021-04-27 22:08
Also FWIW to fix the Mission Editor issue you can follow the instructions here, these worked for me: https://www.digitalcombatsimulator.com/en/support/faq/missions/

Basically you rename the MissionEditor folder in your Saved Games/DCS folder, launch DCS to generate a new one, then copy back your payload and logbook files.

For some reason deleting/renaming the MissionEditor folder also changes your theme (I had Ka-50 selected, it went to default) and some other options, like the cockpit selections in the Special tab, etc.

Those SEEM (not 100% confirmed) to be in the logbook file, which is why it's preferable to rename the old folder rather than deleting it outright.

**Comment by john681611** [comment] 2021-04-28 11:52
More info on broken missions we found the Mig-19 also broke the mission generation if that happened to be in-game.

Try this version: https://github.com/akaAgar/briefing-room-for-dcs/releases/tag/test-net5-210427-1904

**Comment by john681611** [comment] 2021-05-03 21:08
I do apologize we have just discovered why all test builds were breaking. 
Please do try this version:
https://github.com/akaAgar/briefing-room-for-dcs/releases/tag/test-net5-210503-2105

**Comment by john681611** [comment] 2021-07-18 13:14
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.

**Closed by john681611** 2021-07-18 13:14 UTC
Labels: In Beta, bug
