### ISSUE TITLE
Objective Enemy feature units not following objective hide/show option

### ISSUE THREAD

**Issue by Anthon355** [akaAgar/briefing-room-for-dcs#319] opened 2021-12-18 18:51 UTC
units still show on F10 map whereas option is "always hide" in Br (latest bêta)

**Comment by Anthon355** [comment] 2021-12-18 18:53
Bug

**Comment by john681611** [comment] 2021-12-20 20:50
A quick test shows this seems to be working as intended. Can you please attach a template (zipped) as a reliable example?

**Comment by Anthon355** [comment] 2021-12-21 17:31
Hi, here the template.
Thanks.

Le mar. 21 déc. 2021 à 00:50, John Harvey ***@***.***> a
écrit :

**Comment by john681611** [comment] 2021-12-23 11:54
Didn't get anything please don't respond by Email it doesn't work.

**Comment by Anthon355** [comment] 2021-12-23 16:45
sorry, here the zi
[civilt.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/7770502/civilt.zip)
p

**Comment by Anthon355** [comment] 2021-12-24 06:11
same issue on latest beta

**Comment by john681611** [comment] 2021-12-31 17:04
I assume you mean the infantry units that are spawned with the vehicles

**Comment by Anthon355** [comment] 2022-01-02 02:51
ok i understood the difference between units and objectives.  Indeed I think that all enemy units should be hidden and not just objectives with this option.  It reinforces the realism

**Comment by john681611** [comment] 2022-01-03 00:27
Ok so I'll rename this to "Objective Enemy feature units not following objective hide/show option"

**Comment by john681611** [comment] 2022-01-21 21:19
Closing as Released

**Closed by john681611** 2022-01-21 21:19 UTC
Labels: bug, In Beta
