### ISSUE TITLE
Frequencies are not been added into the radio presets. 

### ISSUE THREAD

**Issue by VCW3-admin** [akaAgar/briefing-room-for-dcs#375] opened 2022-02-05 13:38 UTC
###BR Version: 0902 DCS: 2.7.10.19402 Open Beta

### Brief Description: 
 When generating missions, frequencies are not been entered into the preselect in any aircraft. 

### Expected: 
 Can’t remember exactly when this happened but prior to the last couple of beta updated I noticed the frequencies were not been added and need to add them into the mission through the mission editor. 

#### Mission and Template Zip: 

Mission modified: Y/N

**Comment by john681611** [comment] 2022-02-05 19:31
The problem is the complexity of the fact that aircraft have a bunch of radios and on some aircraft like the F/A-18 can do both UHF and VHF on either radio but F-16 has string UHF and VHF radios. These are easy aircraft. More ground orientated aircraft have 4-5 radios.

**Comment by Wood-VCW3** [comment] 2022-02-11 20:27
Noted that particular VHF frequencies added to briefings are the wrong frequencies. 
example: Incirlik | 5-23 | 360.100/129.400 | 109.30/111.70 | 21X
The actual in game VHF frequency for Incirik is 122.1 not 129.40

**Comment by john681611** [comment] 2022-02-11 23:29
Probably mistype if you find more of please please post a PR with fixes  files are under Database>TheaterAirbases

**Comment by john681611** [comment] 2022-03-04 19:05
> The actual in game VHF frequency for Incirik is 122.1 not 129.40

fixed

**Comment by john681611** [comment] 2022-03-07 18:22
Closing this as the original issue won't be fixed due to BR limitations

**Closed by john681611** 2022-03-07 18:22 UTC
Labels: enhancement
