### ISSUE TITLE
Distance integer is awesome but can we make it more than 200?

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#149] opened 2021-04-15 01:31 UTC
We were doing another round of tests last night and wanted to do a loooooong mission, unfortunately the distance integer tops out at 200, giving us a 400nm round trip, is there any way we could raise that up for super long missions?

it all ready works great for long missions and short ones too

**Comment by john681611** [comment] 2021-04-17 16:25
The problem is if we increase it then we will the WW2 and Helo guys unhappy that they keep getting a super long flight for them. So I think the best move is to make it moddable through the Database.

**Comment by john681611** [comment] 2021-04-17 16:52
Unfortunately, this doesn't look like it's possible as the max distance needs to be hard coded at the moment. I don't know what @akaAgar  thinks but I would expect if you want super long trips it may be something to just jump in the editor and move the starting DB or objectives.

**Comment by john681611** [comment] 2021-05-03 21:09
This may now be possible post-re-write of the UI.

**Comment by john681611** [comment] 2021-07-18 13:13
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.

**Closed by john681611** 2021-07-18 13:13 UTC
Labels: enhancement
