### ISSUE TITLE
AV-8B/NA will explode on spawn

### ISSUE THREAD

**Issue by c3f59** [akaAgar/briefing-room-for-dcs#636] opened 2023-02-18 23:21 UTC
### Brief Description: 
AV-8Bs tend to spawn several meters in air and fall down when spawning. They then proceed to explode, which is unfortunate.
Could reproduce when spawning parked on ramp, on solid ground as well as on LHA-1.

### Expected: 
The AV-8B should not fall and explode on spawn. It doesn't when hand placed in Mission Editor.

#### Mission and Template Zip:
[c3f59.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/10775368/c3f59.zip)

Mission modified: N

**Comment by c3f59** [comment] 2023-02-19 09:02
This can be worked around by switching the group to _Takeoff from ground_ and then back to _Takeoff from ramp_. Didn't test if running the mission between these steps is strictly necessary.

**Comment by john681611** [comment] 2023-02-19 18:59
Think this is caused by a international issue making the harriers weight massive and causing it to explode from the "Spawn drop"
 Should be fixed in latest beta please confirm

**Comment by c3f59** [comment] 2023-02-20 17:34
Verified working with `Version 0.5.301.28 (230217-180202)`

**Closed** 2023-02-20 17:34 UTC
Labels: bug, In Beta
