### ISSUE TITLE
AJS-37 as player spawn is broken

### ISSUE THREAD

**Issue by kniqht152** [akaAgar/briefing-room-for-dcs#40] opened 2021-01-12 14:29 UTC
If selecting the AJS-37 as the player flight in a multiplayer or single player game, DCS will crash on load of the generated mission. Additionally opening up the generated mission file in the mission editor shows the AJS-37 to be some form of non playable helicopter rather then a jet that can be assigned a skill level of player.

**Comment by akaAgar** [comment] 2021-01-12 15:37
Oh, you're right! I know what the problem is, I'll fix it today

**Comment by john681611** [comment] 2021-01-17 18:20
Mission loads in my game just getting this error
![image](https://user-images.githubusercontent.com/10814889/104852092-9d563500-58f0-11eb-94e0-12aaefb8fda3.png)

**Comment by akaAgar** [comment] 2021-01-23 13:16
It should be fixed, but I cannot test it for sure as I do not have the AJS-37 module. Could you download the latest release (0.3.101.20) from https://akaagar.itch.io/briefing-room-for-dcs and tell me if it works? Thanks!

**Comment by john681611** [comment] 2021-01-23 15:49
Worked for me in SP when I tried it just before release.

**Comment by akaAgar** [comment] 2021-01-23 16:08
Great! I'm 99% sure what was the cause the problem (a bad UnitFamily value, which made DCS default to AttackHelicopter) as I had the very same problem with another unit, so I mark this as fixed for the moment.

**Closed by akaAgar** 2021-01-23 16:08 UTC
